version: '3.8'

services:
  react-admin-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shadcn-admin-dashboard
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - admin-network
    labels:
      - "com.docker.compose.service=react-admin-dashboard"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy (uncomment if needed)
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - react-admin-dashboard
  #   networks:
  #     - admin-network

networks:
  admin-network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local
